"""add changed_by attribute operator

Revision ID: 4e8a43138d5a
Revises: cd313f16e483
Create Date: 2026-07-27 21:00:51.544516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e8a43138d5a'
down_revision: Union[str, Sequence[str], None] = 'cd313f16e483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flag_versions', sa.Column('changed_by', sa.String(length=100), nullable=False))
    op.alter_column('flag_versions', 'value',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('flag_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_flag_versions_flag_id'), table_name='flag_versions')
    op.add_column('targeting_rules', sa.Column('attribute', sa.String(length=100), nullable=False))
    op.add_column('targeting_rules', sa.Column('operator', sa.String(length=20), nullable=False))
    op.alter_column('targeting_rules', 'target_value',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('targeting_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('targeting_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_targeting_rules_flag_id'), table_name='targeting_rules')
    op.drop_column('targeting_rules', 'rule_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targeting_rules', sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_targeting_rules_flag_id'), 'targeting_rules', ['flag_id'], unique=False)
    op.alter_column('targeting_rules', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('targeting_rules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('targeting_rules', 'target_value',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('targeting_rules', 'operator')
    op.drop_column('targeting_rules', 'attribute')
    op.create_index(op.f('ix_flag_versions_flag_id'), 'flag_versions', ['flag_id'], unique=False)
    op.alter_column('flag_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('flag_versions', 'value',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('flag_versions', 'changed_by')
    # ### end Alembic commands ###
