"""update flag unique constraint

Revision ID: b59de7c916f0
Revises: 4e8a43138d5a
Create Date: 2026-07-30 19:08:11.608218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59de7c916f0'
down_revision: Union[str, Sequence[str], None] = '4e8a43138d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flags_environment_id_flag_key'), table_name='flags')
    op.create_index(op.f('ix_flags_flag_key'), 'flags', ['flag_key'], unique=False)
    op.create_unique_constraint('uq_flags_environment_id_flag_key', 'flags', ['environment_id', 'flag_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_flags_environment_id_flag_key', 'flags', type_='unique')
    op.drop_index(op.f('ix_flags_flag_key'), table_name='flags')
    op.create_index(op.f('ix_flags_environment_id_flag_key'), 'flags', ['environment_id', 'flag_key'], unique=True)
    # ### end Alembic commands ###
