"""create initial tables

Revision ID: cd313f16e483
Revises: 
Create Date: 2026-07-26 21:41:09.255302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd313f16e483'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('previous_data', sa.String(length=2000), nullable=True),
    sa.Column('new_data', sa.String(length=2000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=True)
    op.create_table('user_group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_group_memberships_group_name'), 'user_group_memberships', ['group_name'], unique=False)
    op.create_index(op.f('ix_user_group_memberships_id'), 'user_group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_user_group_memberships_user_id'), 'user_group_memberships', ['user_id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('flag_key', sa.String(length=100), nullable=False),
    sa.Column('flag_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('default_value', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_environment_id'), 'flags', ['environment_id'], unique=False)
    op.create_index(op.f('ix_flags_flag_key'), 'flags', ['flag_key'], unique=True)
    op.create_index(op.f('ix_flags_id'), 'flags', ['id'], unique=False)
    op.create_table('flag_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('change_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flag_versions_flag_id'), 'flag_versions', ['flag_id'], unique=False)
    op.create_index(op.f('ix_flag_versions_id'), 'flag_versions', ['id'], unique=False)
    op.create_table('targeting_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('rule_priority', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=200), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targeting_rules_flag_id'), 'targeting_rules', ['flag_id'], unique=False)
    op.create_index(op.f('ix_targeting_rules_id'), 'targeting_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targeting_rules_id'), table_name='targeting_rules')
    op.drop_index(op.f('ix_targeting_rules_flag_id'), table_name='targeting_rules')
    op.drop_table('targeting_rules')
    op.drop_index(op.f('ix_flag_versions_id'), table_name='flag_versions')
    op.drop_index(op.f('ix_flag_versions_flag_id'), table_name='flag_versions')
    op.drop_table('flag_versions')
    op.drop_index(op.f('ix_flags_id'), table_name='flags')
    op.drop_index(op.f('ix_flags_flag_key'), table_name='flags')
    op.drop_index(op.f('ix_flags_environment_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_user_group_memberships_user_id'), table_name='user_group_memberships')
    op.drop_index(op.f('ix_user_group_memberships_id'), table_name='user_group_memberships')
    op.drop_index(op.f('ix_user_group_memberships_group_name'), table_name='user_group_memberships')
    op.drop_table('user_group_memberships')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
